[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cloelike"
description = "Likelihood module for Euclid primary observables for the CLOE project"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "M. Bonici", email = "marco.bonici@uwaterloo.ca" },
    { name = "G. Cañas-Herrera", email = "canasherrera@strw.leidenuniv.nl" },
    { name = "P. Carrilho", email = "pedro.carrilho@ed.ac.uk" },
    { name = "S. Casas", email = "casas@physik.rwth-aachen.de" },
    { name = "C. Moretti", email = "cmoretti@sissa.it" },
    { name = "A. Pezzotta", email = "andrea.pezzotta@inaf.it" }
]

requires-python = ">=3.12,<3.13"

dynamic = ["version"]

[project.optional-dependencies]
docs = [
    "mkdocs-material>=9.5",
    "mkdocstrings[python]>=0.25",
    "mike>=2.0",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "cloelike/_version.py"

[tool.pytest.ini_options]
addopts = "--verbose --cov=cloelib"

[tool.hatch.metadata]
allow-direct-references = true
