name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  ENV_NAME: cloe-org-env
  ENV_FILE: cloe-org-environments/environments/cloe-org-env-linux-v2026.1.yaml

jobs:
  style:
    name: Style (Lint & Format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: style
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout cloe-org-environments
        uses: actions/checkout@v4
        with:
          repository: cloe-org/cloe-org-environments
          path: cloe-org-environments

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: ${{ env.ENV_NAME }}
          environment-file: ${{ env.ENV_FILE }}
          use-mamba: true

      - name: Configure Git for private repo access
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install cloelib
        run: |
          mamba run -n $ENV_NAME pip install git+https://github.com/cloe-org/cloelib.git

      - name: Install HMCode2020emu
        run: |
          mamba run -n $ENV_NAME pip install git+https://github.com/MariaTsedrik/HMcode2020Emu.git

      - name: Install CAMB
        run: |
          mamba run -n $ENV_NAME pip install camb

      - name: Install astropy
        run: |
          mamba run -n $ENV_NAME pip install astropy

      - name: Install comet-emu
        run: |
          mamba run -n $ENV_NAME pip install comet-emu

      - name: Install cloelike
        run: |
          mamba run -n $ENV_NAME pip install .

      - name: Run tests
        run: mamba run -n $ENV_NAME pytest -vv

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pipx run build
